### ISSUE TITLE
applyStrategy 方法有错误

### ISSUE THREAD

**Issue by anhao** [hyperf-ext/sms#1]
SmsManager.php 
$this->config['default']['senders'] 这个获取不到数据的

make($strategy)->apply($senders)， apply 需要两个参数 

如果VerificationCode类没有设置$sender 或者$senders 就会走到 applyStrategy

**Comment by ericyzhu** [comment]
已修复。

**Comment by anhao** [comment]
applyStrategy 还是有问题的，134行
apply方法需要两个参数
